version: 2
jobs:
  build-release:
    docker:
      - image: circleci/ruby:2.6-rc-node
    working_directory: ~/tmp
    steps:
      - checkout:
          path: workspace/repository
      - run:
          name: Setup environment
            git config --global user.email "till.klocke@connctd.com" && git config --global user.name "Till Klocke"
      - run:
          name: Install dependencies
          command: |
            cd ~/tmp/workspace/repository && bundle install
      - run:
          name: Deploy
          command: |
            cd ~/tmp/workspace/repository && ./deploy.sh

workflows:
  version: 2
  build-release:
    jobs:
      - build-release:
          filters:
            branches:
              only: master