version: 2
jobs:
  build-release:
    docker:
      - image: circleci/ruby:2.6-rc-node
    working_directory: ~/tmp
    steps:
      - checkout:
          path: workspace/repository
      - run:
          name: Deploy
          command: |
            cd ~/tmp/workspace/repository && bundle install && ./deploy.sh

workflows:
  version: 2
  build-release:
    jobs:
      - build-release:
          filters:
            tags:
              only: /.*/